---
title: "Final Project"
author: "Cherie Yu", "Qinyao Xia", "Allison Jiang"
date: "4/22/2019"
output: html_document
---


```{r setup, include=FALSE}
library("knitr")
knitr::opts_chunk$set(echo = FALSE, eval=TRUE, 
                      message=FALSE, warning = FALSE, cache = FALSE) 
options(htmltools.dir.version = FALSE)

library(tidyverse)
library(igraph)
library(dplyr)
library(network)
library(ggplot2)
library(RColorBrewer)
library(readr)
library(ggraph)
library(ggnet)
library(widgetframe)
library(DT)
library(ggnetwork)
library(ggrepel)  
library(quanteda)
library(tm)
library(tidyr)
library(tidytext)
library(stargazer)
library(plotly)
library(rgdal)
library(leaflet)
```  

```{R}
data=read_csv("Nutrition__Physical_Activity__and_Obesity_-_Behavioral_Risk_Factor_Surveillance_System.csv")

fastfood <- read_csv("FastFoodRestaurants.csv")

states <- readOGR("shp/cb_2013_us_state_20m.shp",
  layer = "cb_2013_us_state_20m", GDAL1_integer64_policy = TRUE)
```

```{r}
table(data$YearStart)
table(data$YearEnd)
```

```{r}
table(data$LocationAbbr)
table(data$LocationDesc)
```

```{r}
table(data$Question)
```

```{r}
variable.names(data)
```


### Fast Food Data
```{r}
fastfood_city <- fastfood %>%
  group_by(city) %>%
  summarise(count = n()) %>% 
  arrange(desc(count))
plot1 <- ggplot(fastfood_city[1:20,],aes(x = reorder(city,count),y = count,fill = count)) + geom_bar(stat = 'identity') +
  geom_label(aes(label = count)) +
  theme_minimal(8) +
  labs(x = "City",y = "Count",title = "Top 20 cities in the number of fast-food restaurants") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot1)
```

```{r}
fastfood_province <- fastfood %>%
  group_by(province) %>% 
  summarise("count" = n()) %>% 
  arrange(desc(count))
plot2 <- ggplot(fastfood_province[1:20,],aes(x = reorder(province,count),y = count,fill = count)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = count)) +
  theme_minimal(8) +
  labs(x = "Province", y = "Count",title = "Top 20 province in the number of fast-food restaurants") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot2)
```

```{r}
fastfood_name <- fastfood %>%
  group_by(name) %>% 
  summarise("count" = n()) %>% 
  arrange(desc(count))
plot3 <- ggplot(fastfood_name[1:20,],aes(x = reorder(name,count),y = count,fill = count)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = count)) +
  theme_minimal(8) +
  labs(x = "Name",y = "Count",title = "The top 20 brands in the number of fast-food restaurants") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot3)
```

### Nutrition Data

#### over year line graph
```{r}
data_nation <- data %>%
  filter(LocationDesc == "National") %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)

data_nation_ob <- data_nation %>%
  filter(QuestionID == "Q036" & Total == "Total")

plot4 <- ggplot(data = data_nation_ob, aes(x=YearStart, y=Data_Value)) +
  geom_line()+labs(x = "Year",y = "Percentage of obesity",
                   title = "Percentage of obesity in the US over time")
ggplotly(plot4)
```

```{r}
data_nation_ob_gender <- data_nation %>%
  filter(QuestionID == "Q036" & !is.na(Gender))

plot5 <- ggplot(data = data_nation_ob_gender, aes(x=YearStart, y=Data_Value,
                                                  group=Gender)) +
  geom_line(aes(color=Gender))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of obesity in the US over time by gender") 
ggplotly(plot5)
```

```{r}
data_nation_ob_edu <- data_nation %>%
  filter(QuestionID == "Q036" & !is.na(Education))

plot6 <- ggplot(data = data_nation_ob_edu, aes(x=YearStart, y=Data_Value,
                                                  group=Education)) +
  geom_line(aes(color=Education))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of obesity in the US over time by education")  + 
  scale_color_brewer(palette="Blues")
ggplotly(plot6)
```

```{r}
data_nation_ob_age <- data_nation %>%
  filter(QuestionID == "Q036" & !is.na(`Age(years)`))

plot7 <- ggplot(data = data_nation_ob_age, aes(x=YearStart, y=Data_Value,
                                                  group=`Age(years)`)) +
  geom_line(aes(color=`Age(years)`))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of obesity in the US over time by age") + 
  scale_color_brewer(palette="Blues")
ggplotly(plot7)
```

```{r}
data_nation_ob_inc <- data_nation %>%
  filter(QuestionID == "Q036" & !is.na(Income))

plot8 <- ggplot(data = data_nation_ob_inc, aes(x=YearStart, y=Data_Value,
                                                  group=Income)) +
  geom_line(aes(color=Income))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of obesity in the US over time by income") + 
  scale_color_brewer(palette="Blues")
ggplotly(plot8)
```

```{r}
data_nation_ob_race <- data_nation %>%
  filter(QuestionID == "Q036" & !is.na(`Race/Ethnicity`))

plot9 <- ggplot(data = data_nation_ob_race, aes(x=YearStart, y=Data_Value,
                                                  group=`Race/Ethnicity`)) +
  geom_line(aes(color=`Race/Ethnicity`))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of obesity in the US over time by race") 
ggplotly(plot9)
```

### State in 2014
```{r}
data_ob <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2014) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")


plot10 <- ggplot(data_ob[1:20,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Data_Value)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = Data_Value)) +
  theme_minimal(8) +
  labs(x = "State", y = "Percentage of obesity",title = "Top 20 state in the percentage of obesity in 2014") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot10)
```

```{r}
data_ob_gen <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2014) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(!is.na(Gender))


plot11 <- ggplot(data_ob_gen[1:20,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Gender)) +
  geom_bar(stat = 'identity', position=position_dodge())  +
  labs(x = "State", y = "Percentage of obesity",title = "Top 20 state in the percentage of obesity in 2014 by gender")  +
  coord_flip()
ggplotly(plot11)
```

```{r}
data_ob_edu <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2014) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(!is.na(Education))

plot12 <- ggplot(data_ob_edu[1:40,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Data_Value)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = Data_Value)) +
  theme_minimal(8) +
  labs(x = "State", y = "Percentage of obesity",title = "Top 20 state in the percentage of obesity in 2014 by education") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip() +
  facet_wrap("Education")
ggplotly(plot12)
```

```{r}
data_nation_ac <- data_nation %>%
  filter(QuestionID == "Q043" & Total == "Total")

plot13 <- ggplot(data = data_nation_ac, aes(x=YearStart, y=Data_Value)) +
  geom_line()+labs(x = "Year",y = "Percentage of adults who achieve physical activities",
                   title = "Percent of adults who achieve at least 150 minutes a week 
                   of moderate-intensity aerobic physical activity or 75 minutes a 
                   week of vigorous-intensity aerobic activity (or an equivalent 
                   combination) ")
ggplotly(plot13)
```

```{r}
data_nation_ac_gender <- data_nation %>%
  filter(QuestionID == "Q043" & !is.na(Gender))

plot14 <- ggplot(data = data_nation_ac_gender, aes(x=YearStart, y=Data_Value,
                                                  group=Gender)) +
  geom_line(aes(color=Gender))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of adults who do physical activities") 
ggplotly(plot14)
```

```{r}
data_nation_ac_edu <- data_nation %>%
  filter(QuestionID == "Q043" & !is.na(Education))

plot15 <- ggplot(data = data_nation_ac_edu, aes(x=YearStart, y=Data_Value,
                                                  group=Education)) +
  geom_line(aes(color=Education))+
  labs(x = "Year",y = "Percentage of obesity",
       title = "Percentage of adults who do physical activities")  + 
  scale_color_brewer(palette="Blues")
ggplotly(plot15)
```

```{r}
data_ac <- data %>%
  filter(QuestionID == "Q043" & YearStart == 2013) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")


plot16 <- ggplot(data_ac[1:20,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Data_Value)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = Data_Value)) +
  theme_minimal(8) +
  labs(x = "State", y = "Percentage of adults who do physical activities",title = "Top 20 state in the percentage of adults who do physical activities in 2013") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot16)
```

```{r}
data_ve <- data %>%
  filter(QuestionID == "Q019" & YearStart == 2017) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")


plot17 <- ggplot(data_ve[1:20,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Data_Value)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = Data_Value)) +
  theme_minimal(8) +
  labs(x = "State", y = "Percent of adults who report consuming 
                   vegetables less than one time daily",
title = "Top 20 state in the percentage of obesity adults who report 
consuming vegetables less than one time daily in 2017") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip()
ggplotly(plot17)
```

```{r}
data_ve_edu <- data %>%
  filter(QuestionID == "Q019" & YearStart == 2017) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(!is.na(Education))

plot18 <- ggplot(data_ve_edu[1:40,],aes(x = reorder(LocationDesc,Data_Value),
                                    y = Data_Value,fill = Data_Value)) +
  geom_bar(stat = 'identity') +
  geom_label(aes(label = Data_Value)) +
  theme_minimal(8) +
  labs(x = "State", y = "Percentage of obesity",title = "Top 20 state in the percentage of obesity in 2014 by education") +
  scale_fill_gradient(low = "#FFDAB9",high = "#1E90FF") +
  guides(fill = FALSE) +
  coord_flip() +
  facet_wrap("Education")
ggplotly(plot18)
```

```{r}
library(maps)
```

Mapping fastfood restaurants 
```{r}
fastfood$longitude=ifelse(fastfood$longitude>0,0-fastfood$longitude,fastfood$longitude)
map1=fastfood%>%filter(latitude>25 & latitude<50 & longitude < -50 ) %>% ggplot(aes(x = longitude, y = latitude))+
  geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),fill = "white", color = "dark grey")+
  geom_jitter(alpha = 0.15,color="navy")+
  theme_bw()+
  labs(title = "Fast Food Restaurants in the US (con", x = "Longitudes", y = "Latitudes")
ggplotly(map1)
```

```{r}
map2=fastfood%>%filter(latitude>25 & latitude<50 & longitude < -50 ) %>% 
  filter(name  %in% c("McDonald's","Burger King","Taco Bell","Wendy's"))%>%
  ggplot(aes(x = longitude, y = latitude))+
  geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group),fill = "white", color = "dark grey")+
  geom_point(alpha = 0.15,color=c("navy blue"))+
  theme_bw()+
  labs(title = "Top 4 Fast Food Restaurants in the US", x = "Longitudes", y = "Latitudes")+
  facet_wrap("name")
ggplotly(map2)
```

```{r}
lnglat=data %>%filter(QuestionID == "Q036" & YearStart == 2017) %>%
  filter(Total == "Total")%>%
  select(LocationDesc,GeoLocation)%>%
  na.omit()
names(lnglat)[names(lnglat) == 'LocationDesc'] <- "NAME"
lnglat=separate(lnglat, GeoLocation, into = c("lat", "lng"), sep = ",")
lnglat$lng <- gsub("\\)", "", lnglat$lng)
lnglat$lat <- gsub("\\(", "", lnglat$lat)
lnglat=transform(lnglat, lat = as.numeric(lat), 
               lng = as.numeric(lng))
```

state obesity rates 2011
```{r}
ob11 <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2011) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")
stateob=subset(ob11,LocationDesc!="Guam" & LocationDesc!="National")
stateob$severity=ifelse(stateob$Data_Value<25,"Under 25",ifelse(stateob$Data_Value<30,"25-30"," 30  and up"))
stateob$value=stateob$Data_Value
stateob=transform(stateob, value = as.character(value))
names(stateob)[names(stateob) == 'LocationDesc'] <- "NAME"
obmap=merge(states,stateob,by="NAME")
obmap=merge(obmap,lnglat,by="NAME")

pal = colorFactor("Set1", domain = obmap@data$severity) 

map3=leaflet(obmap)%>%
  setView(-100.0382679, 42.3489054, zoom =4)%>%
  addPolygons(color = "#9b9393", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorFactor("Set1",obmap@data$severity)(obmap@data$severity),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),popup=paste("State: ",obmap$NAME,"<br/>",
                                 "Obesity Rate:",obmap$Data_Value,"<br/>"))%>%
  addLegend(pal=pal,values = ~obmap$severity, title = "State Obesity Rate")%>%
  addCircles(lat=obmap$lat,lng=obmap$lng,label = ~`value`,weight = 2, radius=0.1, color="#ffa500", stroke = TRUE,labelOptions = labelOptions(noHide = T,opacity = 0.8))%>%
  addTiles()
map3
```
state obesity rates 2014
```{r}
ob14 <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2014) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")
stateob=subset(ob14,LocationDesc!="Guam" & LocationDesc!="National")
stateob$severity=ifelse(stateob$Data_Value<25,"Under 25",ifelse(stateob$Data_Value<30,"25-30"," 30  and up"))
stateob$value=stateob$Data_Value
stateob=transform(stateob, value = as.character(value))
names(stateob)[names(stateob) == 'LocationDesc'] <- "NAME"
obmap=merge(states,stateob,by="NAME")
obmap=merge(obmap,lnglat,by="NAME")

pal = colorFactor("Set1", domain = obmap@data$severity) 

map4=leaflet(obmap)%>%
  setView(-100.0382679, 42.3489054, zoom =4)%>%
  addPolygons(color = "#9b9393", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorFactor("Set1",obmap@data$severity)(obmap@data$severity),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),popup=paste("State: ",obmap$NAME,"<br/>",
                                 "Obesity Rate:",obmap$Data_Value,"<br/>"))%>%
  addLegend(pal=pal,values = ~obmap$severity, title = "State Obesity Rate")%>%
  addCircles(lat=obmap$lat,lng=obmap$lng,label = ~`value`,weight = 2, radius=0.1, color="#ffa500", stroke = TRUE,labelOptions = labelOptions(noHide = T,opacity = 0.8))%>%
  addTiles()
map4
```

```{r}
ob17 <- data %>%
  filter(QuestionID == "Q036" & YearStart == 2017) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")
stateob=subset(ob17,LocationDesc!="Guam" & LocationDesc!="National")
stateob$severity=ifelse(stateob$Data_Value<25,"Under 25",ifelse(stateob$Data_Value<30,"25-30"," 30  and up"))
stateob$value=stateob$Data_Value
stateob=transform(stateob, value = as.character(value))
names(stateob)[names(stateob) == 'LocationDesc'] <- "NAME"
obmap=merge(states,stateob,by="NAME")
obmap=merge(obmap,lnglat,by="NAME")

pal = colorFactor("Set1", domain = obmap@data$severity) 

map5=leaflet(obmap)%>%
  setView(-100.0382679, 42.3489054, zoom =4)%>%
  addPolygons(color = "#9b9393", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorFactor("Set1",obmap@data$severity)(obmap@data$severity),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),popup=paste("State: ",obmap$NAME,"<br/>",
                                 "Obesity Rate:",obmap$Data_Value,"<br/>"))%>%
  addLegend(pal=pal,values = ~obmap$severity, title = "State Obesity Rate")%>%
  addCircles(lat=obmap$lat,lng=obmap$lng,label = ~`value`,weight = 2, radius=0.1, color="#ffa500", stroke = TRUE,labelOptions = labelOptions(noHide = T,opacity = 0.8))%>%
  addTiles()
map5
```

obstate and distribution of Fastfood （2017）
```{r}
pop <- paste("Name:",fastfood$name,"<br/>",
             "City:",fastfood$city,"<br/>",
             "Province:",fastfood$province,"<br/>",
             "PostalCode:",fastfood$postalCode,"<br/>")
map6=map5%>%
  addCircleMarkers(lat = fastfood$latitude,lng = fastfood$longitude,popup = pop,weight = 2, radius=0.1,clusterOptions = markerClusterOptions())
map6
```

maybe exercise frequecy matters?
```{r}
ac17 <- data %>%
  filter(QuestionID == "Q043" & YearStart == 2017) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")
stateac=subset(ac17,LocationDesc!="Guam" & LocationDesc!="National")
stateac$level=ifelse(stateac$Data_Value<35,"Under 35",ifelse(stateac$Data_Value<40,"35-40",ifelse(stateac$Data_Value<45,"45-50",ifelse(stateac$Data_Value<55,"50-55","55 and up"))))
stateac$value=stateac$Data_Value
stateac=transform(stateac, value = as.character(value))
names(stateac)[names(stateac) == 'LocationDesc'] <- "NAME"
acmap=merge(states,stateac,by="NAME")
acmap=merge(acmap,lnglat,by="NAME")
pal = colorFactor("Set1", domain = acmap@data$level) 

map7=leaflet(acmap)%>%
  setView(-100.0382679, 42.3489054, zoom =4)%>%
  addPolygons(color = "#9b9393", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorFactor("Set1",acmap@data$level)(acmap@data$level),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),popup=paste("State: ",acmap$NAME,"<br/>",
                                 "Activity Rate:",acmap$Data_Value,"<br/>"))%>%
  addLegend(pal=pal,values = ~acmap$level, title = "State Activity Rate")%>%
  addTiles()%>%
  addCircles(lat=obmap$lat,lng=obmap$lng,label = ~`value`,weight = 2, radius=0.1, color="#ffa500", stroke = TRUE,labelOptions = labelOptions(noHide = T,opacity = 0.8))%>%
  addCircles(lat = fastfood$latitude,lng = fastfood$longitude,popup = pop,weight = 2, radius=40, color="#ffa500", stroke = TRUE, fillOpacity = 0.5)
map7

```


```{r}
ve17 <- data %>%
  filter(QuestionID == "Q019" & YearStart == 2017) %>%
  select(YearStart, LocationDesc, Class, Question, Data_Value, Sample_Size, 
         Total, `Age(years)`, Gender, Education, Income, `Race/Ethnicity`, QuestionID)%>%
  filter(Total == "Total")
stateve=subset(ve17,LocationDesc!="Guam" & LocationDesc!="National")
stateve$level=ifelse(stateve$Data_Value<15,"Under 15",ifelse(stateve$Data_Value<20,"15-20%",ifelse(stateve$Data_Value<25,"25-30%",ifelse(stateve$Data_Value<35,"30-35%","35% and up"))))
stateve$value=stateve$Data_Value
stateve=transform(stateve, value = as.character(value))
names(stateve)[names(stateve) == 'LocationDesc'] <- "NAME"
vemap=merge(states,stateve,by="NAME")
vemap=merge(vemap,lnglat,by="NAME")

pal = colorFactor("Set2", domain = vemap@data$level) 

map8=leaflet(vemap)%>%
  setView(-100.0382679, 42.3489054, zoom =4)%>%
  addPolygons(color = "#9b9393", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorFactor("Set2",vemap@data$level)(vemap@data$level),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),popup=paste("State: ",vemap$NAME,"<br/>",
                                 "Activity Rate:",vemap$Data_Value,"<br/>"))%>%
  addLegend(pal=pal,values = ~vemap$level, title = "Population consuming 
                   vegetables less than one time daily")%>%
  addTiles()%>%
  addCircles(lat=obmap$lat,lng=obmap$lng,label = ~`value`,weight = 2, radius=0.1, color="#ffa500", stroke = TRUE,labelOptions = labelOptions(noHide = T,opacity = 0.8))%>%
  addCircles(lat = fastfood$latitude,lng = fastfood$longitude,popup = pop, weight = 2, radius=40, color="#ffa500", stroke = TRUE, fillOpacity = 0.5)

map8

```

```{r}
#Text Data
#Obesity Tweets
library(stringi)
library(dplyr)
obesity_tweets<-readRDS("obesity_tweets.RDS")
obtweets_location<-with(obesity_tweets, ifelse(place_type=="city", stri_sub(place_full_name, -2, -1), place_full_name))
obtweets_location[c(3, 5)]<-"FL"
obtweets_location[c(22, 23, 114, 115)]<-"PA"
obtweets_location[c(33)]<-"NC"
obtweets_location[35]<-"AK"
obtweets_location[41]<-"MT"
obtweets_location[48]<-"WV"
obtweets_location[c(74, 75, 87)]<-"NY"
obtweets_location[88]<-"NJ"
obtweets_location[c(91)]<-"CO"
obtweets_location[c(129)]<-"CA"
obtweets_location[c(120, 121)]<-"KS"
obtweets_location[128]<-"TN"
obtweets_full<-cbind(obesity_tweets, obtweets_location)
colnames(obtweets_full)[89]<-"place_abbr"

diet_tweets<-readRDS("diet_tweets.RDS")
diet_location<-with(diet_tweets, ifelse(place_type=="city", stri_sub(place_full_name, -2, -1), place_full_name))
diet_location[1]<-"NC"
diet_location[2]<-"MS"
diet_location[c(7, 62, 101)]<-"FL"
diet_location[9]<-"KY"
diet_location[26]<-"OK"
diet_location[29]<-"AR"
diet_location[33]<-"PA"
diet_location[c(39, 86)]<-"SC"
diet_location[47]<-"MT"
diet_location[56]<-"CO"
diet_location[70]<-"WV"
diet_location[83]<-"IN"
diet_location[85]<-"OH"
diet_location[c(89, 90)]<-"NV"
diet_location[92]<-"KS"
diettweets_full<-cbind(diet_tweets, diet_location)
colnames(diettweets_full)[89]<-"place_abbr"

```

```{r}
fastfood_tweets<-readRDS("fastfood_tweets.RDS")
fftweets_location<-with(fastfood_tweets, ifelse(place_type=="city", stri_sub(place_full_name, -2, -1), place_full_name))
fftweets_location[c(2)]<-"CA"
fftweets_location[5]<-"WI"
fftweets_location[c(28)]<-"PA"
fftweets_location[29]<-"NV"
fftweets_full<-cbind(fastfood_tweets, fftweets_location)
colnames(fftweets_full)[89]<-"place_abbr"
```

```{r}
#sentiment analysis of fastfood text 
library(tidytext)
library(dplyr)
library(stringr)
fftweets_words<-tibble(id=fftweets_full$place_abbr, text=fftweets_full$text)
remove_reg <- "&amp;|&lt;|&gt;"
tidy_fftweets <- fftweets_words %>% 
  filter(!str_detect(text, "^RT")) %>%
  mutate(text = str_remove_all(text, remove_reg)) %>%
  unnest_tokens(word, text, token = "tweets") %>%
  filter(!word %in% stop_words$word,
         !word %in% str_remove_all(stop_words$word, "'"),
         str_detect(word, "[a-z]"))
tidyfftwets2<-gsub("^#?", "", tidy_fftweets$word)
tidyfftwets3<-cbind(tidy_fftweets, tidyfftwets2)
colnames(tidyfftwets3)[3]<-"word2"
tidyfftwets3<-tidyfftwets3%>%
  select(id, word2)%>%
  mutate(word = SnowballC::wordStem(word2))%>%
  select(id, word)
fftweets_count<-tidyfftwets3%>%
  count(id, word)
library(tidyr)
ff_sentiments_bing <- fftweets_count %>%
  inner_join(get_sentiments("bing"), by = "word")%>%
  group_by(id, sentiment)%>%
  summarize(pos=sum(n))%>%
  spread(sentiment, pos)%>%
  mutate_all(~replace(., is.na(.), 0))%>%
  mutate(polarity=(positive-negative)/(positive+negative))
library(ggplot2)
ff_sentiments_bing<-ff_sentiments_bing[c(-3, -5), ]
fastfood_plot<-ggplot(ff_sentiments_bing, aes(x=reorder(id, polarity), y= polarity, fill=as.factor(polarity)))+
  geom_bar(stat="identity", alpha=0.5)+
  labs(x="State", y="Polarity Score (BING)", fill="Polarity Score", title="Polarity of Tweets Related to Fastfood by State")+
  coord_flip()
fastfood_plot

neg_sentiment<-c("WA", "PA", "NV", "MI", "CO", "AZ")
neutral_senti<-c("WI", "IL")
pos_sentiment<-c("TX", "SC", "MO", "CA")

pos_fftweets<-fftweets_count%>%
  filter(id %in% pos_sentiment)%>%
  group_by(id)%>%
  arrange(desc(n))
pos_fftweets_subset<-pos_fftweets[1:12,]

```

```{r}
#word cloud for fast food related tweets
fftweets_count2<-fftweets_count%>%
  arrange(desc(n))
fftweets_count_subset<-fftweets_count2[1:15, ]
fastfood_word<-ggplot(fftweets_count_subset, aes(x=reorder(word, n), y=n))+
  geom_bar(stat="identity")+
  coord_flip()+
  labs(title="Fastfood Related Words With Highest Frequency", y="frequency", x="")
fastfood_word
```

```{r}
#Obesity related tweets
colnames(diettweets_full)[89]<-"id"
colnames(obtweets_full)[89]<-"id"
obtweets_full<-rbind(obtweets_full, diettweets_full)
obtweets_words<-tibble(id=obtweets_full$id, text=obtweets_full$text)
remove_reg <- "&amp;|&lt;|&gt;"
tidy_obtweets <- obtweets_words %>% 
  filter(!str_detect(text, "^RT")) %>%
  mutate(text = str_remove_all(text, remove_reg)) %>%
  unnest_tokens(word, text, token = "tweets") %>%
  filter(!word %in% stop_words$word,
         !word %in% str_remove_all(stop_words$word, "'"),
         str_detect(word, "[a-z]"))
tidyobtwets2<-gsub("^#?", "", tidy_obtweets$word)
tidyobtwets3<-cbind(tidy_obtweets, tidyobtwets2)
colnames(tidyobtwets3)[3]<-"word2"
tidyobtwets3<-tidyobtwets3%>%
  select(id, word2)%>%
  mutate(word = SnowballC::wordStem(word2))%>%
  select(id, word)
obtweets_count<-tidyobtwets3%>%
  count(word)

#wordcloud
set.seed(2103)
wordcloud(words = obtweets_count$word, freq = obtweets_count$n,
          max.words=100, random.order=F, colors=brewer.pal(8, "Dark2"))

obtweets_count_state<-tidyobtwets3%>%
  count(id, word)

obesity_sentiments_afinn <- obtweets_count_state %>%
  inner_join(get_sentiments("afinn"), by = "word") %>%
  group_by(id) %>%
  summarize(score = sum(score * n) / sum(n))

library(readxl)
obesity_rate<-read_excel("obesity_data.xlsx")
obesity_rate<-obesity_rate[, -1]

colnames(obesity_rate)[3]<-"id"
combined_df<-inner_join(obesity_sentiments_afinn, obesity_rate, by="id")

obesity_sentiments_afinn<-obesity_sentiments_afinn[c(-8, -31, -34, -38), ]

scatterplot<-ggplot(combined_df, aes(x=score, y=I(Percent*100)))+
  geom_point()+
  geom_smooth()+
  labs(y="Obesity Rate (2017)", x="Sentiment Score (AFINN)", title="Relationship Between Sentiment Towards Obesity and Obesity Rate")
scatterplot


ob_sentiments_bing <- obtweets_count_state %>%
  inner_join(get_sentiments("bing"), by = "word")%>%
  group_by(id, sentiment)%>%
  summarize(pos=sum(n))%>%
  spread(sentiment, pos)%>%
  mutate_all(~replace(., is.na(.), 0))%>%
  mutate(polarity=(positive-negative)/(positive+negative))
ob_sentiments_bing<-ob_sentiments_bing[c(-7, -30, -33, -36), ]
combined_df2<-inner_join(ob_sentiments_bing, obesity_rate, by="id")
plot<-ggplot(combined_df2, aes(x=polarity, y=I(Percent*100)))+
  geom_point(size=2)+
  geom_smooth()+
  labs(y="Obesity Rate (2017)", x="Sentiment Score (Bing)", title="Relationship Between Sentiment Towards Obesity and Obesity Rate")
plot

ob_sentiments_bing2<- obtweets_count_state %>%
  inner_join(get_sentiments("bing"), by = "word")%>%
  group_by(word, sentiment)%>%
  summarize(pos=sum(n))%>%
  spread(sentiment, pos)%>%
  mutate_all(~replace(., is.na(.), 0))

wordcloud(words = ob_sentiments_bing2$word, freq = ob_sentiments_bing2$negative,
          max.words=100, random.order=F, colors=brewer.pal(8, "Dark2"))

```

```{r}
#group states in to high, medium, low obesity rates
obesity_rate2<-obesity_rate%>%
  arrange(desc(Percent))

obesity_rate2$cat<-cut(obesity_rate2$Percent, breaks=3, labels=c("low", "normal", "high"))
combined_full<-inner_join(tidyobtwets3, obesity_rate2, by="id")
obcount_rate<-combined_full%>%
  count(cat, word, sort=T)

obcount_rate_subset1<-obcount_rate%>%
  filter(cat=="high")%>%
  arrange(desc(n))
obcount_rate_subset1<-obcount_rate_subset1[1:15, ]
obcount_rate_subset2<-obcount_rate%>%
  filter(cat=="normal")%>%
  arrange(desc(n))
obcount_rate_subset2<-obcount_rate_subset2[1:15, ]
obcount_rate_subset3<-obcount_rate%>%
  filter(cat=="low")%>%
  arrange(desc(n))
obcount_rate_subset3<-obcount_rate_subset3[1:15, ]
obcount_combined<-rbind(obcount_rate_subset1, obcount_rate_subset2, obcount_rate_subset3)

word_plot<-ggplot(obcount_combined, aes(x=reorder(word, n), y=n, fill=cat))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~cat, ncol = 3, scales = "free") +
  coord_flip() +
  labs(title = "Highest Frequency words in from States with Different Levels of Obesity",
       caption = "Data from Twitter",
       x = NULL, y = "term frequency")
word_plot

```

```{r}
#Are there differences in words that ppl tweet?
library(tidyr)
word_ratios <- combined_full%>%
  count(cat, word)%>%
  group_by(word) %>%
  filter(cat=="high"|cat=="low") %>%
  ungroup()

  
word_ratios<-word_ratios%>%
  spread(cat, n)

word_ratios<-na.omit(word_ratios)

  
word_ratios<-word_ratios%>% 
  mutate(sum_l=sum(low))%>%
  mutate(sum_high=sum(high))%>%
  mutate(num_l=((low+1)/(sum_l+1))) %>%
  mutate(num_high=((high+1)/(sum_high+1)))%>%
  mutate(logratio=log(num_high/num_l))%>%
  arrange(desc(logratio))
z<-word_ratios %>%
  group_by(logratio < 0) %>%
  top_n(10, abs(logratio)) %>%
  ungroup() %>%
  mutate(word = reorder(word, logratio)) %>%
  ggplot(aes(word, logratio, fill = logratio < 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip()+
  labs(title="Tweets Between States With Highest and Lowest Obesity Rates")+
  ylab("log odds ratio (High Obesity/Low Obesity)")+
  scale_fill_discrete(name = "", labels = c("high obesity", "low obesity"))

z

```

```{r}
#bigram analysis
tidy_obtweets_bigram <- obtweets_words %>% 
  filter(!str_detect(text, "^RT")) %>%
  mutate(text = str_remove_all(text, remove_reg)) %>%
  unnest_tokens(bigram, text, token = "ngrams", n=2) 

bigrams_separated <- tidy_obtweets_bigram %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)
bigram_counts<-bigram_counts%>%
  filter(!(word2=="https"))
bigram_counts<-bigram_counts[c(-1, -11), ]

#visualize network of bigrams
library(igraph)
bigram_graph <- bigram_counts %>%
  filter(n > 2) %>%
  graph_from_data_frame()
library(ggraph)
set.seed(2017)
a <- grid::arrow(type = "closed", length = unit(.10, "inches"))

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 4) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1, size=4) +
  theme_void()+
  labs(title="Network of Bigrams in Obesity Related Tweets")

```